backend:
  name: git-gateway
  branch: main # or master

media_folder: "images" # where you want photos saved
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "text"}
          - {label: "About Text", name: "about_text", widget: "markdown"}
